
name: "LuaRocks"
description: "This will download, build, and install lua to the .lua directory in the working directory"

branding:
  icon: 'moon'
  color: 'blue'

inputs:
  luaRocksVersion:
    description: "The version of LuaRocks to install, must be available on https://luarocks.github.io/luarocks/releases/"
    required: false
    default: "3.2.0"

runs:
  using: 'node12'
  main: 'main.js'